module.exports = {
  KEY_TOTEM: 'f9',
  KEY_FIRE: 'f10',
  KEY_HOME: '0',
  KEY_SOS: 'delete',
  KEY_TELEPORT: 'control',
  KEY_ESCAPE: 'escape',
  KEY_UP: 'up',
  KEY_DOWN: 'down',
  KEY_LEFT: 'left',
  KEY_RIGHT: 'right',
  KEY_ENTER: 'enter',
  KEY_MAP: 'm',
  INTERVAL_TOTEM: 60 * 1000 * 5,
  INTERVAL_FIRE: 60 * 1000 * 31,
  FLAG_TOTEM: '.totem',
  FLAG_FIRE: '.fire',
  POS_REBIRTH_1920: { x: 917, y: 610 },
  POS_REBIRTH_1366: { x: 643, y: 480 },
  POS_TRADE_ACCEPT: { x: 1041, y: 967 },
  POS_TRADE_EXCHANGE: { x: 834, y: 377 },
  POS_TRADE_CONFIRM: { x: 1010, y: 567 },
  POS_TRADE_END: { x: 1049, y: 576 },
  POS_PLAYER_HUD: { x: 974, y: 1012 },
  POS_CHANNEL_CONFIRM: { x: 1053, y: 571 },
  CHANNEL_MIN: 1,
  CHANNEL_MAX: 30,
  FIRE_DESKTOP: 'fire-desktop.png',
  FIRE_SAMPLE: 'fire-sample.png',
  CHANNEL_INFO: 'channel-info.png',
  CHANNEL_CROP: 'channel-crop.png'
}
