module.exports = {
  KEY_TOTEM: 'f9',
  KEY_FIRE: 'f10',
  KEY_HOME: '0',
  KEY_SOS: 'delete',
  KEY_TELEPORT: 'control',
  KEY_ESCAPE: 'escape',
  KEY_UP: 'up',
  KEY_DOWN: 'down',
  KEY_LEFT: 'left',
  KEY_RIGHT: 'right',
  KEY_ENTER: 'enter',
  KEY_MAP: 'm',
  INTERVAL_TOTEM: 60 * 1000 * 5,
  INTERVAL_FIRE: 60 * 1000 * 30,
  FLAG_TOTEM: '.totem',
  FLAG_FIRE: '.fire',
  POS_REBIRTH_1920: { x: 917, y: 610 },
  POS_REBIRTH_1366: { x: 643, y: 480 },
  CHANNEL_MIN: 1,
  CHANNEL_MAX: 30,
  FIRE_DESKTOP: 'fire-desktop.png',
  FIRE_SAMPLE: 'fire-sample.png',
  FIRE_STANDARD: 'fire-standard.png'
}
